### ISSUE TITLE
school blocking

### ISSUE THREAD

**Issue by easella** [hypothesis/legacyvia#303]
It is blocked

**Comment by robertknight** [comment]
Hello - Unfortunately we cannot control what sites are allowed by your school. The screenshot that was included in an earlier version of this issue showed that the site was blocked by a "no YouTube" policy. via.hypothes.is does not allow YouTube to be proxied any more, so perhaps the school might reconsider. If you are in a situation where the Via proxy is blocked, you can try using the Chrome extension or Bookmarklet instead. See https://web.hypothes.is/start/ for installation instructions.
